php:
  preset: laravel

css:
    tab-width: 4
    use-tabs: false
    print-width: 80
    double-quotes: false
    finder:
        exclude:
            - node_modules
            - vendor
        name:
            - '*.css'
            - '*.scss'
            - '*.less'

vue:
    tab-width: 4
    use-tabs: false
    print-width: 80
    double-quotes: false
    trailing-commas: es5
    arrow-parens: avoid
    bracket-spacing: true
    finder:
        exclude:
            - node_modules
            - vendor
        name: '*.vue'

js:
    tab-width: 4
    use-tabs: false
    print-width: 80
    double-quotes: false
    trailing-commas: es5
    arrow-parens: avoid
    bracket-spacing: true
    finder:
        exclude:
            - dist
            - node_modules
            - vendor
        name:
            - '*.js'
            - '*.jsx'
        not-name:
            - '*.min.js'
